
-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 13:10:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudio_colaborativo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estudio_colaborativo` ;

-- -----------------------------------------------------
-- Schema estudio_colaborativo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudio_colaborativo` DEFAULT CHARACTER SET utf8 ;
USE `estudio_colaborativo` ;

-- -----------------------------------------------------
-- Table `estudio_colaborativo`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudio_colaborativo`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellido` VARCHAR(30) NOT NULL,
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `pais` VARCHAR(40) NOT NULL,
  `provincia` VARCHAR(40) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `contraseña` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudio_colaborativo`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudio_colaborativo`.`Publicacion` (
  `idPublicacion` INT NOT NULL,
  `texto` VARCHAR(200) NOT NULL,
  `archivo` VARCHAR(80) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `fk_Publicacion_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudio_colaborativo`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudio_colaborativo`.`comentario` (
  `idcomentario` INT NOT NULL,
  `texto` VARCHAR(100) NOT NULL,
  `fecha` DATETIME NULL,
  `Publicacion_idPublicacion` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `Publicacion_idPublicacion`),
  INDEX `fk_comentario_Publicacion1_idx` (`Publicacion_idPublicacion` ASC) VISIBLE,
  INDEX `fk_comentario_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudio_colaborativo`.`Foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudio_colaborativo`.`Foro` (
  `idForo` INT NOT NULL,
  `TipoForo` VARCHAR(35) NOT NULL,
  `Publicacion_idPublicacion` INT NOT NULL,
  PRIMARY KEY (`idForo`),
  INDEX `fk_Foro_Publicacion_idx` (`Publicacion_idPublicacion` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


